# Generated by Django 3.2.5 on 2021-07-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('doctor_link_hash', models.CharField(max_length=255)),
                ('doctor_link_hash_timestamp', models.DateTimeField(auto_now_add=True)),
                ('doctor_info', models.JSONField()),
                ('doctor_order', models.JSONField()),
                ('patient_link_hash', models.CharField(max_length=255)),
                ('patient_link_hash_timestamp', models.DateTimeField(blank=True, null=True)),
                ('patient_confirmation', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
