# Generated by Django 3.2.6 on 2021-08-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_flow', '0002_auto_20210729_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderflow',
            name='auto_doctor_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
