# Generated by Django 3.2.5 on 2021-07-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='unit',
            field=models.CharField(choices=[('PIECES', 'Pieces (เม็ด)'), ('PACKS', 'Packs (แผง)'), ('BOXES', 'Boxes (กล่อง)')], default='PIECES', max_length=6),
        ),
    ]
