# Generated by Django 3.2.6 on 2021-08-06 17:39

from django.db import migrations, models
import django.db.models.deletion
import product.models.product_variation


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0018_auto_20210806_0237'),
        ('product', '0003_productvariation_reject_order_on_duplicate_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='preferred_box_size',
            field=models.ForeignKey(default=product.models.product_variation.get_default_box, on_delete=django.db.models.deletion.PROTECT, to='shipment.boxsize'),
        ),
    ]
