# Generated by Django 3.2.6 on 2021-08-08 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_variation_box_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='repeatable',
            new_name='non_repeatable',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='reject_order_on_duplicate_cid',
        ),
    ]
