# Generated by Django 3.2.5 on 2021-07-24 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_alter_address_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='address.address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
