# Generated by Django 3.2.5 on 2021-08-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_default_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='tel',
        ),
    ]
