# Generated by Django 3.2.5 on 2021-07-26 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('tracking_code', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('shipping_method', models.CharField(max_length=255)),
                ('label_printed', models.BooleanField(default=False)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('note', models.CharField(max_length=255)),
                ('purchase_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('BOOKING', 'Book shipment to Shippop'), ('CONFIRMED', 'Confirmed shipment')], default='BOOKING', max_length=9)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.trackingstatus')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
