# Generated by Django 3.2.5 on 2021-07-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='purchase_id',
            new_name='shippop_purchase_id',
        ),
    ]
