# Generated by Django 3.2.5 on 2021-07-28 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0003_auto_20210727_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='tracking',
        ),
        migrations.RemoveField(
            model_name='trackingstatus',
            name='tracking_code',
        ),
        migrations.AddField(
            model_name='shipment',
            name='courier_tracking_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trackingstatus',
            name='shipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shipment.shipment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackingstatus',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shippop_purchase_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Order for shipment created'), ('BOOKED', 'Book shipment to Shippop'), ('CONFIRMED', 'Confirmed shipment')], default='CREATED', max_length=9),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trackingstatus',
            name='courier_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trackingstatus',
            name='courier_tracking_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trackingstatus',
            name='discount',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='trackingstatus',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='trackingstatus',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
