# Generated by Django 3.2.5 on 2021-07-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0004_auto_20210728_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingstatus',
            name='courier_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
