# Generated by Django 3.2.5 on 2021-07-29 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0006_auto_20210729_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchshipment',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipment.batchshipment'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
