# Generated by Django 3.2.5 on 2021-07-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0007_auto_20210729_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Order for shipment created'), ('BOOKED', 'Book shipment to Shippop'), ('CONFIRMED', 'Confirmed shipment'), ('PRINTED', 'Printed'), ('DELIVERING', 'Delivering'), ('DELIVERED', 'Delivered')], default='CREATED', max_length=10),
        ),
    ]
