# Generated by Django 3.2.5 on 2021-08-03 18:08

from django.db import migrations


def forward(apps, schema_editor):
    box_size_model = apps.get_model('shipment', 'BoxSize')
    box_size_model(
        name='G',
        width=31,
        length=36,
        height=26,
        rank=100
    ).save()


def backward(apps, schema_editor):
    box_size_model = apps.get_model('shipment', 'BoxSize')
    box_size_model.objects.filter(name='G').first().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('shipment', '0011_auto_20210804_0108'),
    ]

    operations = [

        migrations.RunPython(forward, reverse_code=backward),

    ]
