# Generated by Django 3.2.5 on 2021-08-03 18:47

from django.db import migrations, models
import django.db.models.deletion
import shipment.models.box_size


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0012_auto_20210804_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='box_size',
            field=models.ForeignKey(default=shipment.models.box_size.BoxSize.get_default_box_id, null=True, on_delete=django.db.models.deletion.RESTRICT, to='shipment.boxsize'),
        ),
    ]
