# Generated by Django 3.2.5 on 2021-08-04 07:56

import django.db.models.deletion
from django.db import migrations, models

import shipment.models.box_size


class Migration(migrations.Migration):
    dependencies = [
        ('shipment', '0013_alter_shipment_box_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='box_size',
            field=models.ForeignKey(default=1,
                                    on_delete=django.db.models.deletion.RESTRICT, to='shipment.boxsize'),
        ),
    ]
