# Generated by Django 3.2.5 on 2021-08-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0014_alter_shipment_box_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Order for shipment created'), ('FULFILLED', 'Shipment is fulfilled'), ('BOOKED', 'Book shipment to Shippop'), ('CONFIRMED', 'Confirmed shipment')], default='CREATED', max_length=9),
        ),
    ]
