# Generated by Django 3.2.5 on 2021-08-05 14:29


from django.db import migrations
from django.db.migrations import RunPython


def forward(apps, schema_editor):
    box_size_model = apps.get_model('shipment', 'BoxSize')
    default_box_size = apps.get_model('shipment', 'DefaultBoxSize')

    box_size = box_size_model.objects.first()

    default_box_size.objects.create(
        id=1,
        default_box_size_id=box_size.id
    )


def backward(apps, schema_editor):
    default_box_size = apps.get_model('warehouse', 'DefaultBoxSize')
    default_box_size.get(id=1).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('shipment', '0016_defaultboxsize'),
    ]

    operations = [
        RunPython(forward, backward)
    ]
