# Generated by Django 3.2.6 on 2021-08-05 19:37

from django.db import migrations, models
import django.db.models.deletion
import shipment.models.box_size


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0017_default_box_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='box_size',
            field=models.ForeignKey(default=shipment.models.box_size.BoxSize.get_default_box_id, on_delete=django.db.models.deletion.RESTRICT, to='shipment.boxsize'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Order for shipment created'), ('BOOKED', 'Book shipment to Shippop'), ('CONFIRMED', 'Confirmed shipment')], default='CREATED', max_length=9),
        ),
    ]
