# Generated by Django 3.2.6 on 2021-08-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0018_auto_20210806_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shippop_confirm_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
