# Generated by Django 3.2.6 on 2021-08-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0021_auto_20210809_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='courier_code',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
