# Generated by Django 3.2.5 on 2021-08-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_adjustment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
