# Generated by Django 3.2.5 on 2021-07-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=15)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=15)),
                ('house_number', models.CharField(max_length=255)),
                ('subdistrict', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
