# Generated by Django 3.2.5 on 2021-07-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20210728_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=15, null=True),
        ),
    ]
