# Generated by Django 3.2.5 on 2021-07-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('callback_url', models.CharField(max_length=255)),
                ('raw_json_data', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
