# Generated by Django 3.2.5 on 2021-07-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_link', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglink',
            old_name='callback_url',
            new_name='callback_secret',
        ),
    ]
