# Generated by Django 3.2.5 on 2021-07-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_link', '0002_rename_callback_url_shoppinglink_callback_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglink',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
