# Generated by Django 3.2.5 on 2021-08-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
