# Generated by Django 3.2.5 on 2021-07-26 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('address', '0002_alter_address_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('order_by', models.CharField(max_length=255)),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('STARTED', 'Doctor created'), ('CHECKED_OUT', 'Payment is made'), ('EXPIRED', 'More than 24 hr. No effect on stock')], default='STARTED', max_length=11)),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_tel', models.CharField(max_length=11)),
                ('cid', models.CharField(max_length=255)),
                ('order_by', models.CharField(max_length=255)),
                ('order_time', models.DateTimeField(auto_now=True)),
                ('receiver_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
