# Generated by Django 3.2.5 on 2021-07-27 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_rename_purchase_id_shipment_shippop_purchase_id'),
        ('order', '0002_orderitem_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shipment.shipment'),
        ),
    ]
