# Generated by Django 3.2.5 on 2021-07-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderitem_shipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_by',
            new_name='orderer_license',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receiver_tel',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_by',
        ),
        migrations.AddField(
            model_name='order',
            name='orderer_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
