# Generated by Django 3.2.5 on 2021-07-30 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orderitem_product_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receiver_name',
        ),
    ]
