# Generated by Django 3.2.5 on 2021-08-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_receiver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='fulfilment_status',
            field=models.IntegerField(choices=[(0, 'UNFULFILLED'), (1, 'FULFILLED')], default=0),
        ),
    ]
