# Generated by Django 3.2.5 on 2021-08-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_orderitem_fulfilment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='fulfilment_status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'FULFILLED'), (2, 'CANCELLED')], default=0),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['fulfilment_status', 'product_variation'], name='order_order_fulfilm_2c5b38_idx'),
        ),
    ]
