# Generated by Django 3.2.5 on 2021-08-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_orderitem_fulfill_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='line_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='telemed_session_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
