# Generated by Django 3.2.6 on 2021-08-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20210805_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Doctor created'), ('CHECKED_OUT', 'Payment is made'), ('EXPIRED', 'More than 24 hr. No effect on stock'), ('CANCELLED', 'Cancelled')], default='STARTED', max_length=11),
        ),
    ]
